-- CREATE DATABASE hist IF DONT EXIST --

CREATE TABLE calc(
    n1 DECIMAL NOT NULL,
    n2 DECIMAL NOT NULL,
    operation VARCHAR(3) NOT NULL,
    result DECIMAL NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

